#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS =  -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -c -std=c++11 -pthread
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS) -std=c++11 -pthread
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/CAMPMMT_Server0511

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2 -std=c++11 -pthread
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -std=c++11 -pthread
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/CAMPMMT_Server0511

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/MySocketUNIX-v2.o $(OBJDIR_DEBUG)/CAMPServerSession-v1.o $(OBJDIR_DEBUG)/CAMPServerQoSManager-v1.o $(OBJDIR_DEBUG)/CAMPCallSetupManager-v1.o $(OBJDIR_DEBUG)/CAMPSender-v1.o $(OBJDIR_DEBUG)/CAMPMPULoader-v1.o $(OBJDIR_DEBUG)/CAMPMMTPModule-v1.o $(OBJDIR_DEBUG)/CAMPFECEncoder-v1.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/MySocketUNIX-v2.o $(OBJDIR_RELEASE)/CAMPServerSession-v1.o $(OBJDIR_RELEASE)/CAMPServerQoSManager-v1.o $(OBJDIR_RELEASE)/CAMPCallSetupManager-v1.o $(OBJDIR_RELEASE)/CAMPSender-v1.o $(OBJDIR_RELEASE)/CAMPMPULoader-v1.o $(OBJDIR_RELEASE)/CAMPMMTPModule-v1.o $(OBJDIR_RELEASE)/CAMPFECEncoder-v1.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(OBJ_DEBUG) $(LIB_DEBUG) -o $(OUT_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/MySocketUNIX-v2.o: MySocketUNIX-v2.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MySocketUNIX-v2.cpp -o $(OBJDIR_DEBUG)/MySocketUNIX-v2.o

$(OBJDIR_DEBUG)/CAMPServerSession-v1.o: CAMPServerSession-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPServerSession-v1.cpp -o $(OBJDIR_DEBUG)/CAMPServerSession-v1.o

$(OBJDIR_DEBUG)/CAMPServerQoSManager-v1.o: CAMPServerQoSManager-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPServerQoSManager-v1.cpp -o $(OBJDIR_DEBUG)/CAMPServerQoSManager-v1.o

$(OBJDIR_DEBUG)/CAMPCallSetupManager-v1.o: CAMPCallSetupManager-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPCallSetupManager-v1.cpp $(LDFLAGS_DEBUG) -o $(OBJDIR_DEBUG)/CAMPCallSetupManager-v1.o

$(OBJDIR_DEBUG)/CAMPSender-v1.o: CAMPSender-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPSender-v1.cpp -o $(OBJDIR_DEBUG)/CAMPSender-v1.o

$(OBJDIR_DEBUG)/CAMPMPULoader-v1.o: CAMPMPULoader-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPMPULoader-v1.cpp -o $(OBJDIR_DEBUG)/CAMPMPULoader-v1.o

$(OBJDIR_DEBUG)/CAMPMMTPModule-v1.o: CAMPMMTPModule-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPMMTPModule-v1.cpp -o $(OBJDIR_DEBUG)/CAMPMMTPModule-v1.o

$(OBJDIR_DEBUG)/CAMPFECEncoder-v1.o: CAMPFECEncoder-v1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CAMPFECEncoder-v1.cpp -o $(OBJDIR_DEBUG)/CAMPFECEncoder-v1.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/MySocketUNIX-v2.o: MySocketUNIX-v2.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MySocketUNIX-v2.cpp -o $(OBJDIR_RELEASE)/MySocketUNIX-v2.o

$(OBJDIR_RELEASE)/CAMPServerSession-v1.o: CAMPServerSession-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPServerSession-v1.cpp -o $(OBJDIR_RELEASE)/CAMPServerSession-v1.o

$(OBJDIR_RELEASE)/CAMPServerQoSManager-v1.o: CAMPServerQoSManager-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPServerQoSManager-v1.cpp -o $(OBJDIR_RELEASE)/CAMPServerQoSManager-v1.o

$(OBJDIR_RELEASE)/CAMPCallSetupManager-v1.o: CAMPCallSetupManager-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPCallSetupManager-v1.cpp $(LDFLAGS_RELEASE) -o $(OBJDIR_RELEASE)/CAMPCallSetupManager-v1.o

$(OBJDIR_RELEASE)/CAMPSender-v1.o: CAMPSender-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPSender-v1.cpp -o $(OBJDIR_RELEASE)/CAMPSender-v1.o

$(OBJDIR_RELEASE)/CAMPMPULoader-v1.o: CAMPMPULoader-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPMPULoader-v1.cpp -o $(OBJDIR_RELEASE)/CAMPMPULoader-v1.o

$(OBJDIR_RELEASE)/CAMPMMTPModule-v1.o: CAMPMMTPModule-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPMMTPModule-v1.cpp -o $(OBJDIR_RELEASE)/CAMPMMTPModule-v1.o

$(OBJDIR_RELEASE)/CAMPFECEncoder-v1.o: CAMPFECEncoder-v1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CAMPFECEncoder-v1.cpp -o $(OBJDIR_RELEASE)/CAMPFECEncoder-v1.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

